name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3f3b4eeb8bd35f7d1f5f0d52a29f6307a

    # Light snake
    - name: Generate Light Snake
      uses: Platane/snk/svg-only@756e4a04e0783dcbbaa026f3a0c2eedf2a32a9d8
      with:
        github_user_name: "Sumitkolgire23"
        outputs: dist/light.svg

    # Dark snake
    - name: Generate Dark Snake
      uses: Platane/snk/svg-only@756e4a04e0783dcbbaa026f3a0c2eedf2a32a9d8
      with:
        github_user_name: "Sumitkolgire23"
        outputs: dist/dark.svg
        palette: github-dark

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@312a52f6b09b7be1c1ea53d30de063008c33c3c0
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
