name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde74da5cd3ad9742f8d2b2b4b3c6e2e6a3df

    - name: Generate snake animations
      uses: Platane/snk/gh-pages@v3
      with:
        github_user_name: Sumitkolgire23
        outputs: |
          dist/light.svg
          dist/dark.svg
        palette: |
          github-light
          github-dark

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@78c156f2895aaeac035fdfd01c48f76e99283a0a
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
