name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate summary cards
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Sumitkolgire23
          STARRED_COUNT: true

      - name: Commit summary cards
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update summary cards" || echo "No changes"
          git push
